//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Клиент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Клиент()
        {
            this.Объект = new HashSet<Объект>();
        }

        [Display(Name = "ID Клиента")]
        public int ID_клиента { get; set; }
        public string Город { get; set; }
        public string Адрес { get; set; }
        public string Телефон { get; set; }
        public string Почта { get; set; }

        [Display(Name = "Контактное лицо")]
        public string Контактное_лицо { get; set; }

        [Display(Name = "Название организации")]
        public string Название_организации { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Объект> Объект { get; set; }
    }
}
