//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Материал
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Материал()
        {
            this.Материал_объекта = new HashSet<Материал_объекта>();
            this.Состав_закупки = new HashSet<Состав_закупки>();
        }

        [Display(Name = "ID Материала")]
        public int ID_материала { get; set; }
        public string Наименование { get; set; }

        [Display(Name = "Вид товара")]
        public string Вид_товара { get; set; }
        public Nullable<int> Количество { get; set; }

        [Display(Name = "Единицы измерения")]
        public string Единицы_измерения { get; set; }

        [Display(Name = "Минимальное количество")]
        public Nullable<int> Минимальное_количество { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Материал_объекта> Материал_объекта { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_закупки> Состав_закупки { get; set; }
    }
}
