//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Сотрудник
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудник()
        {
            this.Работа_на_объекте = new HashSet<Работа_на_объекте>();
        }

        [Display(Name = "ID сотрудника")]
        public int ID_сотрудника { get; set; }
        public string Должность { get; set; }
        public Nullable<int> Стаж { get; set; }
        public string Телефон { get; set; }
        public Nullable<int> Оклад { get; set; }
        public string ФИО { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Работа_на_объекте> Работа_на_объекте { get; set; }
    }
}
