//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Этап_выполнения
    {
        [Display(Name = "ID объекта")]
        public int ID_объекта { get; set; }

        [Display(Name = "ID этапа")]
        public int ID_этапа { get; set; }

        [System.ComponentModel.DataAnnotations.DataType(System.ComponentModel.DataAnnotations.DataType.Date)]
        [System.ComponentModel.DataAnnotations.DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Дата")]
        public Nullable<System.DateTime> Дата { get; set; }

        [Display(Name = "Название этапа")]
        public string Название_этапа { get; set; }
    
        public virtual Объект Объект { get; set; }
    }
}
